### ISSUE TITLE
git: completion failing wih alias

### ISSUE THREAD

**Issue by Mikilio** [rsteube/carapace-bin#2235]
Git completion fails at https://github.com/rsteube/carapace-bin/blame/d2cd58e5846f5408cd00e212c9634e32f024b8e3/pkg/actions/tools/git/alias.go#L34.

The command line looks like this after typing `git <Tab>`:
```
git panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/rsteube/carapace-bin/pkg/actions/tools/git.Aliases({0x0, 0x0}, {0x0, 0x0})
        github.com/rsteube/carapace-bin/pkg/actions/tools/git/alias.go:34 +0x53e
github.com/rsteube/carapace-bin/completers_release/git_completer/cmd.addAliasCompletion({0xc000446c20, 0xc000446c20?, 0x1})
        github.com/rsteube/carapace-bin/completers_release/git_completer/cmd/root.go:334 +0x17a
github.com/rsteube/carapace-bin/completers_release/git_completer/cmd.init_root.func3(0x60df80?, {0xc000446c20, 0x1, 0x1})
        github.com/rsteube/carapace-bin/completers_release/git_completer/cmd/root.go:322 +0x4a
github.com/rsteube/carapace.Carapace.PreRun.func1(0xc000446c20?, {0xc000446c20, 0x1, 0x1})
        github.com/rsteube/carapace@v0.49.1/carapace.go:34 +0x56
github.com/rsteube/carapace._storage.preRun(0xc000446c20?, 0x25993a3?, {0xc000446c20, 0x1, 0x1})
        github.com/rsteube/carapace@v0.49.1/storage.go:117 +0xf3
github.com/rsteube/carapace.traverse(0x354fe00, {0xc000446c20?, 0x1, 0x1})
        github.com/rsteube/carapace@v0.49.1/traverse.go:15 +0x155
github.com/rsteube/carapace.complete(0x354fe00?, {0xc000446c00, 0x3, 0x3})
        github.com/rsteube/carapace@v0.49.1/complete.go:42 +0x9bc
github.com/rsteube/carapace.addCompletionCommand.func1(0xc0003cb800, {0xc000446c00?, 0x3, 0x3})
        github.com/rsteube/carapace@v0.49.1/command.go:42 +0x31c
github.com/spf13/cobra.(*Command).execute(0xc0003cb800, {0xc000446c00, 0x3, 0x3})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x354fe00)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/rsteube/carapace-bin/completers_release/git_completer/cmd.Execute()
        github.com/rsteube/carapace-bin/completers_release/git_completer/cmd/root.go:259 +0x485
github.com/rsteube/carapace-bin/cmd/carapace/cmd.executeCompleter({0x7ffd74ff7fea, 0x0?})
        github.com/rsteube/carapace-bin/cmd/carapace/cmd/completers_release.go:932 +0x6b7
github.com/rsteube/carapace-bin/cmd/carapace/cmd.invokeCompleter({0x7ffd74ff7fea, 0x3})
        github.com/rsteube/carapace-bin/cmd/carapace/cmd/invoke.go:230 +0x125
github.com/rsteube/carapace-bin/cmd/carapace/cmd.oldInvoke(0x0?, {0xc0000a0b80, 0x4, 0x4})
        github.com/rsteube/carapace-bin/cmd/carapace/cmd/invoke.go:139 +0x8b5
github.com/rsteube/carapace-bin/cmd/carapace/cmd.glob..func4(0xc0001a0200?, {0xc0000a0b80?, 0x4?, 0x24da40d?})
        github.com/rsteube/carapace-bin/cmd/carapace/cmd/invoke.go:32 +0x18
github.com/spf13/cobra.(*Command).execute(0x345c940, {0xc0000160b0, 0x4, 0x4})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x345c940)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/rsteube/carapace-bin/cmd/carapace/cmd.glob..func7(0xc0001a0400?, {0xc0000160b0?, 0x7?, 0x24da40d?})
        github.com/rsteube/carapace-bin/cmd/carapace/cmd/root.go:93 +0x516
github.com/spf13/cobra.(*Command).execute(0x345da80, {0xc0000160b0, 0x4, 0x4})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x345da80)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/rsteube/carapace-bin/cmd/carapace/cmd.Execute({0x2918f0c?, 0xc0000061a0?})
        github.com/rsteube/carapace-bin/cmd/carapace/cmd/root.go:175 +0x33e
main.main()
        github.com/rsteube/carapace-bin/cmd/carapace/main.go:11 +0x25

```
Indeed, the Array returned from `strings.SplitN` can be smaller than n.

My aliases look like the following:
```
   5   │[alias]
   6   │     backport = "cherry-pick -x"
   7   │     blame = "-w -M"
   8   │     comma = "commit --amend"
   9   │     force-push = "push --force-with-lease"
  10   │     get = "clone --recursive"
  11   │     pr = "!\"pr() { git fetch origin pull/$1/head:pr-$1; git checkout pr-$1; }; pr\"\n"
  12   │     publish = "!git pull && git push"
  13   │     rb = "rebase origin/HEAD"
  14   │     recommit = "!git commit -eF $(git rev-parse --git-dir)/COMMIT_EDITMSG"
  15   │     reset-pr = "reset --hard FETCH_HEAD"
  16   │     uncommit = "reset --soft HEAD^"
  17   │     update = "!git pull && git submodule update --init --recursive"
```

**Comment by Mikilio** [comment]
The issue seems to be caused by my newline in line 11. Removing it solves the issue for me. If multiline aliases are not intended for support, this can be closed.
